/**
 * Map GhoulStats part ids → node names as loaded by Three.js from the Unity GLB.
 * UnityGLTF sanitizes names: spaces → `_`, so "Eye Socket" becomes "Eye_Socket".
 */
export const UNITY_PART_NAMES: Record<string, string | string[]> = {
  halo: 'Halo',
  mowhawk: 'Mowhawk',
  candle: 'Candle',
  dirt: 'Dirt',
  nightcap: 'Nightcap_New',
  circlet: 'Circlet',
  redHorns: ['Red_Horns', 'Red_Horns_(1)'],
  loldefi: ['loldefi_Hat', 'loldefi_'],
  positronic: 'Positronic',
  crown: 'Crown',
  fleshner: 'StrictlyBusinessHair',
  rag: 'Rag',
  toxicHead: 'ToxicHead',
  tatteredCloak: ['TatteredCloak_webgl', 'TatteredCloak'],
  innerCircle: ['InnerCloak_webgl', 'InnerCloak'],
  bullHorns: 'BullHorns',
  redacted: 'RedactedBar',
  jaysGlasses: 'JayPegs',
  eyeSocket: 'Eye_Socket',
  perforated: ['Perforated', 'Perforated_(1)', 'Perforated_(2)'],
  punctured: ['Punctured', 'Punctured_(1)'],
  melonGlasses: 'MelonGlasses',
  blueViper: 'Glasses_-_BlueViper',
  riffRaff: 'Glasses_-_RiffRaff',
  nc69r: 'nc69r',
  xeKF420: 'xeKF420',
  bandage: 'Bandage',
  patch: 'eyepatch',
  eyeBlood: ['DischargeBlood', 'EyeDischarge_Blood'],
  eyeGunk: 'DischargeGunk',
  eyeTears: 'Discharge_Tears',
  mouthBlood: 'Blood_Mouth',
  mouthSludge: 'Sludge_Mouth',
  arrow: 'Arrow',
  rose: 'Rose',
  cig: 'Cig1',
  cig2: 'Cig2',
  torch: 'Torch',
  blade: 'Knife',
  cross: 'Cross',
  stogie: 'Stogie',
  key: 'Key',
  idol: 'Idol',
  vaporwaveTea: 'tea',
  doodle: 'cat',
  infernalFlame: ['Infernal_Flame', 'Infernal_Flame_(1)', 'Infernal_Flame_1'],
  flames: 'Flames',
  beams: 'Beam',
  crayon: 'Crayon',
  drallHorns: ['Drall_Horns', 'Drall_Horns_2'],
  lilBHat: 'lilB_Hat',
  lilBGlasses: 'lilB_Glasses',
  santaHat: 'SantaHat',
  candyCane: 'CandyCane',
  staceyAxe: 'tomahawk',
  sudoGems: 'SudoGems',
  rayGhoul: 'RayHead',
  ghoulPegs: 'JayHair',
  oldOne: 'OldOne',
  dreamer: 'Dreamer',
  cudi: 'Cudi',
  // IDK unique lives under one group in the Unity GLB (no separate Candle/Glasses nodes)
  idkCandle: 'IDK_Group',
  idkGlasses: 'IDK_Group',
  idkGunk: 'IDK_Group',
  idkParticleGroup: 'IDK_Group',
};

/** eyesGroup children */
export const UNITY_EYE_GROUPS = [
  'SmallEyes',
  'FullEyes',
  'PeerEyes',
  'RedPeerEyes',
  'WhiteEyes',
  'BasedEyes',
  'BeadyEyes',
  'DialatedEyes',
  'PoppedEyes',
  'EvilEyes',
  'RolledEyes',
  'CyclopsStareEyes',
  'CyclopsEyes',
  'LookingBackEyes',
  'uWuEyes',
  'GlareEyes',
];

/** Sockets — also sanitized by UnityGLTF */
export const UNITY_SOCKETS = [
  'Top_Head_Acc',
  'Top Head Acc',
  'LowerEyeAcc',
  'MouthAcc',
  'LowerHeadAcc',
  'MidHeadAcc',
  'MidEyeAcc',
  'Special',
  'TopEyeAcc',
  'Powerful',
  'Cranium',
  'eyesGroup',
  '1/1',
  '1_1',
  'IDK',
];

export const UNITY_ALWAYS_HIDE = [
  'Halo_Light',
  'Halo Light',
  'Based_Ghoul_Head_-_Teeth',
  'Based Ghoul Head - Teeth',
  'PLACEHOLDER_Patch',
  'InfernalFlamePLACEHOLDER',
  'BeamsPLACEHOLDER',
  'Magica_Capsule_Collider_Eyes',
  'Magica Capsule Collider Eyes',
  'Magica_Capsule_Collider_(MouthAcc)',
  'Magica Capsule Collider (MouthAcc)',
  'Collider_-_Head',
  'Collider - Head',
  'Collider_-_Head_(1)',
  'Collider - Head (1)',
  'Collider_-_Head_(2)',
  'Collider - Head (2)',
  'VFX_TorchLight',
];
